### ISSUE TITLE
Setting headers doesn't work with Swoosh Adapter

### ISSUE THREAD

**Issue by solnic** [elixir-saas/resend-elixir#1]
Hey there! I fail to see how to set headers via Swoosh and from what I can tell it seems like it's just not supported yet. Any chance this could be added soon?

**Comment by jtormey** [comment]
Hey! I must have missed the notification when you opened this issue. I've added support for a `:headers` opt in [4266945](https://github.com/elixir-saas/resend-elixir/commit/4266945f325e74851be4da9986a992181d2a7586). Now published in v0.4.2.
